image: chef/chefdk:latest

stages:
  - Test
  - Merge
  - Deploy
  
Rubocop:
  stage: Test
  script:
    - rubocop ./

Cookstyle:
  stage: Test
  script:
    - cookstyle site_cookbooks/
  
Foodcritic:
  stage: Test
  script:
    - foodcritic site_cookbooks/

Berks:
  stage: Test
  script:
    - apt-get -qq update
    - apt-get -qq install git -y
    - for d in ./site_cookbooks/*/ ; do (cd "$d" && berks install); done
    - for d in ./site_cookbooks/*/ ; do (cd "$d" && berks verify); done
    - for d in ./site_cookbooks/*/ ; do (cd "$d" && berks outdated); done
  
Old_Berks:
  stage: Test
  script:
    - apt-get -qq update
    - apt-get -qq install git -y
    - berks install
    - berks verify
    - berks outdated

ChefSpec:
  stage: Test
  script:
    - for d in ./site_cookbooks/*/ ; do (cd "$d" && chef exec rspec); done
  allow_failure: true
