image: chef/chefdk:latest

stages:
  - Lint
  - Test
  - Smoke Test
  - Merge
  - Deploy
  
Rubocop:
  stage: Lint
  script:
    - rubocop utils/

Cookstyle:
  stage: Lint
  script:
    - cookstyle cookbooks/
  
Foodcritic:
  stage: Lint
  script:
    - foodcritic cookbooks/ -t ~FC075

Berks:
  stage: Test
  script:
    - apt-get -qq update
    - apt-get -qq install git -y
    - for d in ./cookbooks/*/ ; do (echo "Testing $d" && cd "$d" && berks install && berks verify && berks outdated); done
  
Old_Berks:
  stage: Test
  script:
    - apt-get -qq update
    - apt-get -qq install git -y
    - berks install
    - berks verify
    - berks outdated

ChefSpec:
  stage: Test
  script:
    - chef gem install docker-api --version '= 1.34.0'
    - for d in ./cookbooks/*/ ; do (echo "Testing $d" && cd "$d" && chef exec rspec --force-color -fd); done

BoK Dry Run:
  stage: Smoke Test
  script:
    - for bok in applications/*.y*l ; do (echo "Testing $bok" && mu-deploy -d $bok); done
  tags: 
    - mu-master