image: chef/chefdk:latest

stages:
  - Lint
  - Test
  - Merge
  - Deploy
  
Rubocop:
  stage: Lint
  script:
    - rubocop utils/

Cookstyle:
  stage: Lint
  script:
    - cookstyle cookbooks/
  
Foodcritic:
  stage: Lint
  script:
    - foodcritic cookbooks/ -t ~FC075

Berks:
  stage: Test
  script:
    - apt-get -qq update
    - apt-get -qq install git -y
    - for d in ./cookbooks/*/ ; do (cd "$d" && berks install); done
    - for d in ./cookbooks/*/ ; do (cd "$d" && berks verify); done
    - for d in ./cookbooks/*/ ; do (cd "$d" && berks outdated); done
  
Old_Berks:
  stage: Test
  script:
    - apt-get -qq update
    - apt-get -qq install git -y
    - berks install
    - berks verify
    - berks outdated

ChefSpec:
  stage: Test
  script:
    - for d in ./cookbooks/*/ ; do (cd "$d" && chef exec rspec); done
  allow_failure: true
