  - name: drupaldb
    engine: mysql
    dns_sync_wait: false
    vpc:
      nat_ssh_user: <%= $nat_ssh_user %>
<% if $vpc_deploy_id %>
      deploy_id: <%= $vpc_deploy_id %>
<% else %>
      vpc_name: vpc
<% end %>
      subnet_pref: all_private
    size: db.t2.medium
    storage: 5
    port: 3306
