--- 
<%
  $azs = MU::Cloud::AWS.listAZs
  current_vpc = MU.myVPC
%>
admins: 
  - 
    email: xyz@example.com
    name: xyz
appname: demo
loadbalancers: 
  - 
    listeners: 
      - 
        instance-port: 80
        instance-protocol: HTTP
        lb-port: 80
        lb-protocol: HTTP
    name: demo
    region: us-east-1
server_pools: 
  - 
    basis: 
      launch-config: 
        name: demo
        server: portal
        size: t1.micro
    loadbalancers: 
      - 
        concurrent-load-balancer: demo
    max-size: 4
    min-size: 2
    name: autoscale_demo
    ssh_user: ubuntu
    zones: 
      - us-east-1b
      - us-east-1c
      - us-east-1d
servers: 
  - 
    ingress_rules: 
      - 
        hosts: 
          - 0.0.0.0/0
        port: 80
      - 
        hosts: 
          - 0.0.0.0/0
        port: 443
    name: portal
    platform: ubuntu
    run_list: 
      - "recipe[apache2]"
    size: m3.medium
    ssh_user: ubuntu
    storage: 
      - 
        size: 15
    vpc:
    <% if $vpc_deploy_id then %>
      deploy_id: <%= $vpc_deploy_id %>
    <% elsif current_vpc %>
      vpc_id: <%= current_vpc %>
      subnet-pref: public
    <% else %>
      vpc_name: vpc
      subnets:
      <% (1..$azs.size).each do |i| %>
        - subnet_name: Subnet<%= i-1 %>Public
      <% end %>
    <% end %>
<% unless $vpc_deploy_id or current_vpc then %>
vpcs:
- name: vpc
  route-tables:
  - name: internet
    routes:
     - destination_network: 0.0.0.0/0
       gateway: "#INTERNET"
  subnets:
<% $azs.each.with_index do |az, i| %>
  - name: Subnet<%= i %>Public
    ip_block: 10.0.<%= i %>.0/24
    availability-zone: "<%= az %>"
    route-table: internet
<% end %>
<% end %>

